repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: docs/requirements.txt
    -   id: trailing-whitespace
        exclude: docs/requirements.txt
-   repo: https://github.com/psf/black
    rev: 23.9.0
    hooks:
    -   id: black
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.291
    hooks:
    -   id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
